#version: "3.8"

services:
  postgres:
    container_name: idea_database
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=idea
    ports:
      - "5432:5432"